version: '3.8'

services:
    frontend:
        image: node:16-alpine3.11
        container_name: frontend
        volumes:
            - './:/app'
        working_dir: /app
        ports:
            - '8080:3000'
        command:
            - /bin/sh
            - -c
            - |
                sleep infinity
                npm i
                npm run dev
