version: '3.8'

services:
    backend:
        image: node:16-alpine3.11
        container_name: backend
        volumes:
            - './:/app'
        working_dir: /app
        ports:
            - '3001:3001'
        command:
            - /bin/sh
            - -c
            - |
                npm i
                npm run dev
